services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app           # Mount source code for hot reload
      - /app/node_modules        # Anonymous volume to prevent node_modules overwrite
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app          # Mount source code for hot reload
      - /app/node_modules        # Anonymous volume to prevent node_modules overwrite
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
